FROM golang:1.13.1-alpine as builder

# Create gopxe user (needs to match host)
RUN adduser -u 2000 -D -g 2000 gopxe

RUN mkdir -p /go/src/gopxe
ADD . /go/src/gopxe
WORKDIR /go/src/gopxe
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -a -installsuffix cgo -mod=vendor -o gopxe .

RUN mkdir -p /gopxe/public
RUN mkdir -p /gopxe/ksTempl
RUN chown -R gopxe /gopxe

ADD --chown=gopxe ./public /gopxe/public
ADD --chown=gopxe ./ksTempl /gopxe/ksTempl

FROM scratch
EXPOSE 9090 9090/udp

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group

USER gopxe

COPY --chown=gopxe --from=builder /go/src/gopxe/gopxe /gopxe/gopxe
COPY --chown=gopxe --from=builder /gopxe /gopxe
WORKDIR /gopxe

ENTRYPOINT ["/gopxe/gopxe"]
